FROM python:3.13.0b3-slim
WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD cd src && sleep 5 && gunicorn -b 0.0.0.0:8001 main:app -k uvicorn.workers.UvicornWorker